import { db, auth } from './firebase-init.js';
import { collection, getDocs, orderBy, query } from 'https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js';
const fn='https://us-central1-smartcutservices-9ce54.cloudfunctions.net/';
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={apps:[],pricing:[],consultations:[]};
async function token(){const u=auth.currentUser;if(!u)throw Error('Session administrateur requise.');return u.getIdToken();}
async function call(name,body){const r=await fetch(fn+name,{method:'POST',headers:{Authorization:`Bearer ${await token()}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||d.error||'Opération impossible');return d;}
function notice(t,error=false){$('#notice').textContent=t;$('#notice').style.color=error?'#a52d25':'#0d7665';}
async function load(){const [doctors,pharmacies,labs,prices,consults,catalogResponse]=await Promise.all([getDocs(collection(db,'healthDoctorApplications')),getDocs(collection(db,'pharmacyApplications')),getDocs(collection(db,'healthLabApplications')),getDocs(collection(db,'healthConsultationPricing')),getDocs(query(collection(db,'healthAppointments'),orderBy('createdAt','desc'))),fetch(`${fn}healthGetConsultationCatalog`).then(r=>r.ok?r.json():null).catch(()=>null)]);state.apps=[...doctors.docs.map(x=>({id:x.id,type:'doctor',...x.data()})),...pharmacies.docs.map(x=>({id:x.id,type:'pharmacy',...x.data()})),...labs.docs.map(x=>({id:x.id,type:'laboratory',...x.data()}))];const overrides=new Map(prices.docs.map(x=>[x.id,{id:x.id,...x.data()}]));state.pricing=(catalogResponse?.specialties||[]).map(s=>overrides.get(s.code)||{id:s.code,specialtyCode:s.code,prices:s.prices||{essential:0,advanced:0}});state.consultations=consults.docs.map(x=>({id:x.id,...x.data()}));render();}
function render(){const pending=state.apps.filter(x=>['submitted','pending'].includes(String(x.status).toLowerCase()));$('#pendingCount').textContent=pending.length;$('#verifiedCount').textContent=state.apps.filter(x=>x.status==='verified').length;$('#consultationCount').textContent=state.consultations.length;$('#refundCount').textContent=state.consultations.filter(x=>String(x.status).includes('REFUND')).length;$('#applicationsList').innerHTML=state.apps.length?state.apps.map(x=>`<div class="row"><div><strong>${esc(x.profile?.professionalName||x.profile?.businessName||x.profile?.name||x.id)}</strong><br><small>${esc(x.type)} · ${esc(x.status||'draft')}</small></div><span>${esc(x.applicationNumber||'')}</span><span class="badge">${esc(x.profile?.specialty||x.profile?.address||'')}</span><div class="actions">${pending.includes(x)?`<button class="approve" data-review="verified" data-type="${esc(x.type)}" data-uid="${esc(x.id)}">Valider</button><button class="reject" data-review="rejected" data-type="${esc(x.type)}" data-uid="${esc(x.id)}">Refuser</button>`:''}</div></div>`).join(''):'Aucune candidature.';$('#pricingList').innerHTML=state.pricing.length?state.pricing.map(x=>`<div class="row"><strong>${esc(x.specialtyCode)}</strong><div class="field"><label>Essentiel<input data-price="essential" data-id="${esc(x.id)}" value="${esc(x.prices?.essential)}"></label><label>Avancé<input data-price="advanced" data-id="${esc(x.id)}" value="${esc(x.prices?.advanced)}"></label><label>Commission %<input data-price="commission" data-id="${esc(x.id)}" value="${esc(x.commissionRate??15)}"></label><button class="approve" data-save-price="${esc(x.id)}">Enregistrer</button></div></div>`).join(''):'Les tarifs par défaut sont utilisés.';$('#consultationsList').innerHTML=state.consultations.length?state.consultations.slice(0,100).map(x=>`<div class="row"><strong>${esc(x.specialtyName||x.planName||'Consultation')}</strong><span>${esc(x.status)}</span><span>${esc(x.amount)} HTG</span><small>${esc(x.patientUid||'')}</small></div>`).join(''):'Aucune consultation.';}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));});
document.addEventListener('click',async e=>{const r=e.target.closest('[data-review]');if(r){try{await call('healthAdminReviewProfessional',{type:r.dataset.type,uid:r.dataset.uid,status:r.dataset.review});notice('Candidature mise à jour.');await load();}catch(x){notice(x.message,true);}}const p=e.target.closest('[data-save-price]');if(p){try{const id=p.dataset.savePrice;await call('healthAdminSaveConsultationPricing',{specialtyCode:id,essential:Number(document.querySelector(`[data-price="essential"][data-id="${id}"]`).value),advanced:Number(document.querySelector(`[data-price="advanced"][data-id="${id}"]`).value),commissionRate:Number(document.querySelector(`[data-price="commission"][data-id="${id}"]`).value)});notice('Tarif enregistré.');await load();}catch(x){notice(x.message,true);}}});
document.addEventListener('adminAccessGranted',()=>load().catch(e=>notice(e.message,true)),{once:true});if(document.body.dataset.adminAccess==='granted')load().catch(e=>notice(e.message,true));
